name: cache_video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android With Cache capability.
repository: https://github.com/mohsenzamani22/video_player.git

version: 0.0.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.video.player
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  pedantic: ^1.11.1
  pigeon: ^1.0.7
